# Generated by Django 5.1.4 on 2024-12-10 17:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=4)),
                ('professor', models.CharField(max_length=100)),
                ('keywords', models.TextField(blank=True)),
                ('prerequisites', models.ManyToManyField(blank=True, to='mammoth_course_compass_algo.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField(blank=True)),
                ('overall', models.FloatField(blank=True, null=True)),
                ('materials', models.IntegerField(help_text='Rate the quality of instruction and teaching effectiveness', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('course_content', models.IntegerField(help_text='Rate the quality and relevance of course materials and content', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('workload', models.IntegerField(help_text='Rate the manageability of assignments and workload (1 = very easy, 5 = very difficult)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('difficulty', models.IntegerField(help_text='Rate the difficulty level (1 = very easy, 5 = very difficult)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professor', models.IntegerField(help_text='Rate how engaging, helpful the professor was', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('would_take_again', models.BooleanField(default=None, help_text='Would you take this course again?', null=True)),
                ('attendance_mandatory', models.BooleanField(default=None, help_text='Was attendance mandatory?', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mammoth_course_compass_algo.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
