# Generated by Django 5.1.1 on 2024-12-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "author_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pub_date", models.DateTimeField(blank=True, null=True)),
                ("host", models.TextField(blank=True, null=True)),
                (
                    "link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "picture_link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("event_description", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("categories", models.TextField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("map_location", models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
